/**
 * @module Employee
 * Core domain models for employee data and state transitions.
 */

import type { Department } from "./Departments";

/**
 * Main Employee entity.
 */
export interface Employee {
  readonly id: string; 
  readonly fullName: string;
  readonly salary: number;
  readonly birthDate: string; // Format: YYYY-MM-DD (ISO 8601)
  readonly department: Department;
  readonly avatar?: string;
}

/**
 * Data required to create a new employee.
 * We omit 'id' because it's usually generated by the backend.
 */
export interface NewEmployee extends Omit<Employee, "id"> {}

/**
 * Structure for partial updates.
 * Forces inclusion of 'id' while making all other fields optional.
 */
export interface EmployeeUpdatePayload {
  readonly id: string;
  readonly changes: Partial<NewEmployee>;
}

/**
 * Helper type for filtering employees in the UI.
 */
export interface EmployeeFilter {
  readonly search?: string;
  readonly department?: Department | "All";
  readonly minSalary?: number;
  readonly maxSalary?: number;
}